### ISSUE TITLE
Article sélectionner n'existe pas 

### ISSUE THREAD

**Issue by LeFrancais7** [Mysterious-Developers/InfinIdea#36]
Quand on est sur l'onglet explorer qu'un article nous intéresse qu'on veut en savoir plus, on clique dessus l'image ce met en warning et nous indique que l'article n'existe pas ou a été supprimer. 

https://infinidea.veagle.fr/article.php?id=6343107658838

**Comment by pierrbt** [comment]
C'est bon, il y avait une erreur pour savoir si l'article existait ou pas il y avait un faux négatif
